FROM node:22-alpine

WORKDIR /app

# 1) Install deps first (cache layer)
COPY package*.json ./
RUN npm install

# 2) Copy the rest of the code
COPY server.js .
COPY rate-limit/ ./rate-limit/
COPY routes/ ./routes/
COPY ecosystem.config.js .

# 3) Install PM2
RUN npm install -g pm2

EXPOSE 3001

# 4) Start only the dev PM2 app
CMD ["pm2-runtime", "start", "ecosystem.config.js", "--only", "app-dev"]
