FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install --omit=dev

COPY server.js .
COPY rate-limit/ ./rate-limit/
COPY routes/ ./routes/
COPY ecosystem.config.js .

RUN npm install -g pm2

EXPOSE 3000

CMD ["pm2-runtime", "start", "ecosystem.config.js", "--only", "app-prod"]
